- include/klee/ExecutionState.h
- include/klee/IncompleteSolver.h
- include/klee/Solver.h
- include/klee/SolverImpl.h
- lib/Core/ExecutionState.cpp
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/ITree.cpp
- lib/Core/ITree.h
- lib/Core/TimingSolver.cpp
- lib/Core/TimingSolver.h
- lib/Solver/CachingSolver.cpp
- lib/Solver/CexCachingSolver.cpp
- lib/Solver/FastCexSolver.cpp
- lib/Solver/IncompleteSolver.cpp
- lib/Solver/IndependentSolver.cpp
- lib/Solver/QueryLoggingSolver.cpp
- lib/Solver/QueryLoggingSolver.h
- lib/Solver/Solver.cpp
All functionalities are implemented and tested working on small examples in [feliciahalim/klee-examples] (https://github.com/feliciahalim/klee-examples.git), resulting in search-space reduction, most significantly for Regexp.c example from KLEE's tutorial which I have included in my other pull request for [feliciahalim/klee-examples] (https://github.com/feliciahalim/klee-examples.git).
> First version of Tracer-X

- include/klee/Interpreter.h
- lib/Core/BlockTable.cpp
- lib/Core/BlockTable.h
- lib/Core/Executor.cpp
- lib/Core/Executor.h
- lib/Core/ITree.cpp
- lib/Core/ITree.h
- tools/klee/main.cpp
This adds more detailed statistics on subsumed paths and tests, error paths and tests, etc. Also included a preliminary version of visited basic blocks recording, still to be worked on.
> Added More Detailed Statistics

- lib/Core/ITree.cpp
- lib/Core/ITree.h
- lib/Solver/Solver.cpp
It seems to run correctly on `loop_safe.c`. Still need to test if it runs correctly on feliciahalim/klee-examples basic examples. It currently fails on `addition_safe6.c`.
> Polished the Implemention of Existential Simplification

- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/Executor.cpp
- lib/Core/ITree.cpp
- lib/Core/ITree.h
- lib/Solver/Solver.cpp
This PR solves issue #31. Note that this also subsumes PR #37.
> Fix to Missing Interpolant Constraint Issue

- lib/Solver/Z3Builder.cpp
Otherwise build fails with new Z3.
> Updated Z3Builder.cpp with newer Z3 API.

- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
@domainexpert  Fixing bug of load value from the pointer, specifically to fix the problem in https://github.com/feliciahalim/klee-examples/blob/master/basic/argument2.c
> Bugfix: load value from pointer

- lib/Core/Dependency.cpp
This allows basic/malloc1.c of feliciahalim/klee-examples#21 to be run without problems.
> Added support for malloc call in Depedency::execute

- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/Executor.cpp
- lib/Core/ITree.cpp
- lib/Core/ITree.h
Correct fix to issue #49 . Now both feliciahalim/klee-examples/basic/addition_unsafe1.c and feliciahalim/klee-examples/basic/loop_unsafe1.c show error report.
> Fix to Issue #49

- README.md
To resolve this issue: https://github.com/feliciahalim/klee/issues/56
> Resolve issue#56: Project Subtitle Needs Updating

- lib/Core/ITree.cpp
- lib/Core/ITree.h
> Made Some Subsumption Statistics Reported in Two-Decimal Points

- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/Executor.cpp
- lib/Core/ITree.cpp
- lib/Core/ITree.h
To test this branch, please use `echonosyscall` from https://github.com/tracer-x/klee-examples/commit/cf3069f532650cbce81014f39fca68370b04caaf and use commands which located in the comment of header file.
> Fix to run echo (no system call) with merged with issue number 42

- lib/Core/Dependency.cpp
This should generally resolve #53 and make coreutils experiments more stable.
> Added default external function handler in Dependency::execute

- include/klee/Interpreter.h
- lib/Core/Executor.cpp
- lib/Core/ITree.cpp
- lib/Core/ITree.h
- tools/klee/main.cpp
.. can be printed in the INFO file
> Move dumpInterpolationStats to Main.cpp, so the subsumption statistics

- lib/Core/Executor.cpp
- lib/Core/ITree.cpp
- lib/Core/ITree.h
> Renamed SearchTree class to ITreeGraph

- include/klee/Internal/Module/VersionedValue.h
- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/TxTree.cpp
- lib/Core/TxTree.h
- lib/Core/VersionedValue.cpp
Added mechanism to propagate small string of reason for inclusion of memory datum in the subsumption entry table, for outputting with `-debug-subsumption`.
> Debug reason

- include/klee/Internal/Module/VersionedValue.h
- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/TxTree.cpp
- lib/Core/TxTree.h
Mainly by proliferating the use of references to avoid copying of data structures.
> Various performance optimizations

- lib/Core/TxTree.cpp
For when concrete contents match in SubsumptionTableEntry::subsumed.
> Added more debug info 

- lib/Core/TxTree.cpp
- lib/Core/TxTree.h
> Fix to slowness issue for basic/pointer_struct5.c

- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/Executor.cpp
- lib/Core/TxTree.cpp
- lib/Core/TxTree.h
@rasoolmaghareh This resolves issue #243.
> Corrected handling of symbolic addresses in memory bounds check and interpolation

- lib/Core/Dependency.cpp
Tracer-X sometimes terminate with the following error:
```
While deleting: [6 x i8]* %.str
Use still stuck around after Def is destroyed:  <badref> = getelementptr inbounds [6 x i8]* @.str, i32 0, i32 0
klee: /usr/local/lib/llvm-3.4.2/src/lib/IR/Value.cpp:79: virtual llvm::Value::~Value(): Assertion `use_empty() && "Uses remain when a value is destroyed!"' failed.
0  klee            0x0000000000f556e2 llvm::sys::PrintStackTrace(_IO_FILE*) + 50
1  klee            0x0000000000f54e54
2  libpthread.so.0 0x00002ac9a86ef390
3  libc.so.6       0x00002ac9aaf61428 gsignal + 56
4  libc.so.6       0x00002ac9aaf6302a abort + 362
5  libc.so.6       0x00002ac9aaf59bd7
6  libc.so.6       0x00002ac9aaf59c82
7  klee            0x0000000000f012ef
8  klee            0x0000000000eecbb6 …
```
> Avoided the use of getAsInstruction() in Dependency.cpp

- include/klee/CommandLine.h
- lib/Basic/CmdLineOptions.cpp
- lib/Core/Dependency.cpp
- lib/Core/Executor.cpp
This command line option is important when the user wants to get the skeleton tree.
> Added -no-bound-check command line argument

- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/Executor.cpp
- lib/Core/TxTree.cpp
- lib/Core/TxTree.h
- test/Feature/LowerSwitch.c
> Fix to memory bounds interpolation in special function

- include/klee/Internal/Module/TxValues.h
- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/TxStore.cpp
- lib/Core/TxTree.cpp
- lib/Core/TxValues.cpp
While working on #278, I made several general fixes, that may be immediately beneficial.
> Trivial fixes

- include/klee/Solver.h
- lib/Core/Dependency.cpp
- lib/Core/Dependency.h
- lib/Core/Executor.cpp
- lib/Core/TimingSolver.cpp
- lib/Core/TimingSolver.h
- lib/Core/TxValues.cpp
- lib/Solver/Solver.cpp
> Handling of switch instruction

- include/klee/Internal/Module/TxValues.h
- lib/Core/Dependency.h
Various small fixes while working on #298 that can be immediately applied.
> Assorted fixes

- lib/Core/TxStore.cpp
> Fixing the bug in leftOfEntry where its inconsistent with usedByLeft Path and usedByRightPath

- include/klee/CommandLine.h
- lib/Basic/CmdLineOptions.cpp
- lib/Core/Executor.cpp
Fixed the comments made by you in #346
> Adding a command line option for emitting all errors in same path. 

- lib/Core/Executor.cpp
- lib/Core/Executor.h
Hi Rasool, I have updated the code for BB coverage.
Please have a check.
Thank you!
> Update BB Coverage & re-format source codes

- lib/Core/Executor.cpp
https://github.com/tracer-x/klee/issues/363#event-3208941364
Hi @rasoolmaghareh , please check again before merging. Thanks.
> Add speculation safety fix:

- lib/Core/Executor.cpp
- lib/Core/TxTree.cpp
@rasoolmaghareh I made a fix in checking global values in case it is of void type.
Can you check and merge to master, thank you?
> Skip checking global for void type

- include/klee/CommandLine.h
- lib/Basic/CmdLineOptions.cpp
- lib/Core/TxDependency.cpp
- lib/Core/TxTree.cpp
> Add mark global option

- lib/Core/TxTree.cpp
- lib/Core/TxWP.cpp
- lib/Core/Z3Simplification.cpp
The base is the master branch (after merging) and recent commits are cherrypicked from new-wpinterpolant branch.
> Updates on new-wpinterpolant

- lib/Core/TxTree.cpp
This PR is to solve Issue #398.
> mark WP vars during WPInstantiation
