lib/Core/Executor.cpp, test/Feature/DanglingConcreteReadExpr.c
Added -no-interpolation option to KLEE. In addition, `make check` usually succeeds for this revision, however, `Dogfood/ImmutableSet.cpp` would likely fail occasionally.
=> Added -no-interpolation option to KLEE

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Executor.cpp, tools/kleaver/main.cpp
I made sure that when both STP and Z3 supports are enabled (compiled in), the interpolation routines are only called when Z3 was selected. I have also added printing on which is the solver used.
=> Refined the Conditions for Solver Selection

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/ITree.cpp
This PR contains two bugfixes. The first issue causes a memory access error in some examples, whereas the second issue causes assertion violation in the `Dependency` class, as the return value of a PHI node could not be found.
=> Handle Empty Query in Subsumption Check and Added Memory Dependency Tracking for PHI Nodes

lib/Core/Executor.cpp
Compilation error occurs when `--with-z3=...` is specified as an argument to `configure` and `--with-stp=...` isn't. This PR fixed it.
=> Fixed compilation error when --with-stp is not specified

lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Solver/CexCachingSolver.cpp, lib/Solver/Solver.cpp
The implementation of the simplifier is applicable only for limited cases currently, so I have added several if conditions in the methods' body to check for the conditions under which it is applicable. I think it is still important to develop tests for this procedure, as the conditions may not capture all cases where it is not applicable.
=> Added Conditions in SubsumptionTableEntry::simplifyArithmeticBody

lib/Core/ITree.cpp
The failure was triggered when the substitution clauses (equality constraints) is a proper DNF containing disjunctions. In the future, we should actually support disjunctive equality constraints.
=> Fixed Assertion Failure

lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
The `tree.dot` file is a DOT file of the symbolic execution tree. Enable its generation using `-output-tree` option. This option is currently only effective when Z3 interface is compiled in and interpolation is enabled (not switched off using `-no-interpolation` option). To get the PDF file `tree.pdf` from `tree.dot`, say `dot -Tpdf tree.dot -o tree.pdf`. On Ubuntu, this requires the installation of `graphviz` package.
=> Added Generation of tree.dot in KLEE Output Directory

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/ITree.cpp, lib/Core/ITree.h
Also added detailed comment block for Dependency class for documenting its functionality.
@feliciahalim I updated the old header comments in ITree.[h,cpp]. This means removing `Author: felicia` line from those headers. FYI, some are in the opinion that it is a better practice not to name source files. As you know, there are no author names in KLEE source files. In any case, your contributions are recorded in the commit history anyway.
=> Added header comments to Dependency.[h,cpp], ITree.[h,cpp]

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h, tools/klee/main.cpp
This PR contains several improvements, namely (slightly) faster subsumption table index that managed to cut off several seconds (on my machine) from the run of KLEE's Tutorial 2 `Regexp.x` example. Also included simplifications on statistics generation and displaying for interpolation functionalities. In addition, `-interpolation-time-stat` has been changed to `-interpolation-stat` as the statistics now doesn't just display timings.
=> Faster Subsumption Table Indexing and Simplified Interpolation Statistics

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
Without this fix, basic/arraysimple2.c and basic/arraysimple3.c in feliciahalim/klee-examples#20 will throw assertion violation from within LLVM. Also cleaned up and simplified the interface of abstract dependency transition implementations in Dependency.[cpp,h].
=> Fixed incorrect recording of incoming block for PHI nodes

lib/Core/Executor.cpp
@domainexpert  when the branch can only go one way or concrete non-symbolic condition, subsequent data values are actually control-dependent on the condition. So the values in such conditions should be marked as core values to be considered at subsumption checks
=> Refined Condition for Marking Branch Condition as Core

lib/Core/ITree.cpp
For the case when the query simplifies to false. This speeds up Tracer-X runs at least for bubble sort (compare `make bubble.klee` and `make bubble.stpklee` in feliciahalim/klee-examples/basic).
=> Quick return in SubsumptionTableEntry::subsumed

lib/Core/ITree.cpp, lib/Core/ITree.h
For resolving issue #39 . Now klee-examples/basic/addition_safe8.c has 2 subsumptions instead of 0 (as previously). In general, this patch results in more subsumptions without losing error report, however, some examples became slightly slower. Following is relevant statistics from running klee-examples/basic examples.
```
addition.c
BEFORE: 0.07user 0.00system 0:00.08elapsed 95%CPU (0avgtext+0avgdata 33392maxresident)k
KLEE: done:     subsumed paths = 2
AFTER: 0.07user 0.01system 0:00.09elapsed 96%CPU (0avgtext+0avgdata 32960maxresident)k
KLEE: done:     subsumed paths = 2
addition_safe1.c
BEFORE: 0.12user 0.00system 0:00.12elapsed 100%CPU (0avgtext+0avgdata 33408maxresident)k
KLEE: done:     subsumed paths = 4
AFTER: 0.10user 0.00system 0:00.11elapsed 100%CPU (0avgtext+0avgdata …
```
=> Added Simple Substitution of Existential with Universal

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Dependency.cpp, lib/Core/ITree.cpp
@feliciahalim @nguyenquocbinh This PR Introduces `-no-existential` option to avoid existential quantification in subsumption check by equating each existential variable with its corresponding free variable. For example, when checking if x < 10 is subsumed by another state where there is x' s.t., x' <= 0 && x = x' + 20 (here the existential variable x' represents the value of x before adding 20), we strengthen the query by adding the constraint x' = x. This has an effect of removing all existentially-quantified variables most solvers are not very powerful at solving, however, at likely less number of subsumptions due to the strengthening of the query.
=> Option to Eliminate Quantifiers By Strengthening Subsumption Check Query

lib/Core/Dependency.cpp, lib/Core/Dependency.h
@domainexpert  storesList field vector is changed into `unordered_map` because in `Dependency.cpp` it iterates to find the suitable allocation so if we change it to `unordered_map` it become `[allocation, VersionedValue] `so we just need to find the key allocation, and get the corresponding `VersionedValue`.
The first attempt is change vector into map at optimize branch. However, it didn't improved much mainly because `std::map` also requires `O(log n)` to search the key. So, the second attempt is to use `unordered_map` which has average constant time `O(1)` for searching in collection.
This is the experiment results : [here](https://docs.google.com/document/d/1VWmnCJuKE6ImdtTNJDPP-z7QOdLt3lkwxQ54oHkOtyA/edit?usp=sharing)
I tried for tr examples that doesn't require max-time configuration …
=> Change storesList data structure

lib/Core/ITree.cpp
@domainexpert The last result shows the number of subsumption were 2 instead of 4. It seems we able to still get 4 subsumptions by changing 2 things:
1. I noticed in` ITree.cpp `line 1241, there's variable substitution for the `interpolant` and I think it will be useful if we could do the variable substitution to the `equalities` as well. In this case, we can get the opportunity to replace `shadow expression `with its `non shadow expression` that we have obtained from the `substitution mapping`.
2. In the `simplifyArithmeticBody` method, I add one `if` condition that process the `interpolant` that has `existential` variable in it.
I have tested this PR on basic examples and `Regexp`.c, this PR only increase the subsumption rates in addition_safe8. But, it doesn't affect other subsumption …
=> Applying Substitution for Further Simplification of Existential Formula Used in Subsumption Check

lib/Core/ITree.cpp, lib/Core/ITree.h
The interpolation tree graph is the `tree.pdf` generated in the KLEE output directory after a run. Numbering the subsumption edges eases debugging especially when matching the edges with the debug log to check the correctness of the subsumption.
=> Added Subsumption Edge Numbering In the Interpolation Tree Graph

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
This is a resolution of issue #42 . Previous field-insensitive flow dependency tracking to compute unsatisfiability core's dependent-upon allocations loses precision due to field-insensitivity of load and store for composite allocations. Changed the dependency computation mechanism to use concrete load/store addresses provided by KLEE as much as possible, although on small occassions the addresses are symbolic, in which case a logic formula similar to *ite* expression is constructed in subsumption checks. This results in simpler-to-solve and *more importantly* correct formulas in subsumption checks, and it enhances the running speed very significantly. This PR is not fully tested, and therefore incomplete, which preferably should not be allowed, but this is a special occassion as I will …
=> Replacement of Field Insensitivity with Concrete Addresses

lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
Also renamed `ITree::checkCurrentStateSubsumption` to simpler `ITree::subsumptionCheck`.
=> Added Profiling for Number of Solver Calls per Subsumption Check

include/klee/Expr.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h, lib/Expr/Expr.cpp, lib/Expr/ExprPPrinter.cpp, lib/Expr/ExprSMTLIBPrinter.cpp, lib/Solver/Z3Builder.cpp, lib/Solver/Z3Builder.h
Comparing memory allocations (representing program state) is important in subsumption checks. Sometimes, however, the allocations are referenced via symbolic (non-constant) address. Test cases in tracer-x/klee-examples#30 exhibit issues with the current handling symbolic addresses, which is fixed in this PR. For the basic examples https://github.com/tracer-x/klee-examples/tree/master/basic , this PR resulted in no loss in error reports (previous: 5, new: the same 5). The number of subsumptions, however differ in 2 examples: `basic/bubble.c` (previous: 6, now: 4) and `basic/regexp_nonrecursive2.c` (previous: 26, now: 27), however, the new 4 subsumptions in bubble.c are more effective in reducing search space than the previous 6, as they succeed earlier in the execution. As a result, the …
=> Fix to Issues in Handling of Symbolic Addresses

lib/Core/ITree.cpp, lib/Core/ITree.h
This PR is related to issue : https://github.com/tracer-x/klee/issues/80
For basic example, the execution time has improved in general especially for `regexp_nonrecursive2` from 0.68s into 0.50s and `arraysimple6` from 0.30s to 0.24s without affecting the subsumption rates.
For `bubble` and `tr` group example with most execution time 120s, both execution time and subsumption rates looks similar between both branches.
For `regexp` example, the execution time is also improved from 281s to 274s without affecting subsumption rates.
For `grading-examples/count`, the execution time is also improved from 2s to 0.14s without affecting subsumption rates.
=> Add a preSolving method in the subsumed method to takeover simple cases instead of calling the actual solver

lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
This PR is related to https://github.com/tracer-x/klee/issues/81. 
The result shows there is execution time improvement for` scalability/regexp` example from 281.09 to 130.75 without affecting subsumption and error rates.
For `bubble` and `tr` group example, execution time performance looks similar with master branch, both subsumption rates does not differ with result from the master branch. I also noticed non-deterministic behavior in `bubble9_unsafe` where the subsumptions can be 2 or 0 at other time.
For `basic example`, the execution time improvement can also be slightly seen in some examples without affecting the number of subsumption and error rates.
=> Remove PathConditionMarker and move getStoredExpressions method from subsumed method

lib/Core/ITree.cpp, lib/Core/ITree.h
Specifically:
* Renamed SubsumptionTableEntry::solvingUnaryConstraints to SubsumptionTableEntry::detectConflictPrimitives.
* Renamed SubsumptionTableEntry::getSimplifiableConjuncts to SubsumptionTableEntry::fetchQueryEqualityConjuncts.
* Simplifed logic in both methods.
* Polished comments for SubsumptionTableEntry::detectConflictPrimitives and SubsumptionTableEntry::fetchEqualityConjuncts.
Running time profiles are generally about the same before and after modification for the basic examples in https://github.com/klee-examples/basic/, if not slightly faster with the modification. Running with `loop_unsafe1.c` is markedly faster with 0.09s for this PR compared to 0.38s previously (user time). The basic examples have the same subsumption and error counts.
=> Simplified logic in solvingUnaryConstraints and geSimplifiableConjuncts

README.md
Reverts tracer-x/klee#88
@feliciahalim I realized that this PR would cause issues in that it makes `tracer-x-no-abstract-no-clpr`'s commits set no longer a subset of `master`, so I request for its reversion. The problem is, when we made changes to this branch, and then merge the changes to `master` or  `tracer-x-clpr`, we will always have to change the `README.md`.
=> Revert "Updating the Readme.md to explain the branch tracer-x-no-abstract-no-clpr"

autoconf/configure.ac, include/klee/Solver.h
Just two small typos in `configure.ac` and `Solver.h`.
=> Two Small Typos

lib/Core/Dependency.cpp, lib/Core/Executor.cpp
This is fixes for run-time error when executing `cat` in `coreutils-6.10`. Please use updated version of https://github.com/tracer-x/klee-examples/tree/coreutils as I have updated the `Makefile` that able to run cat with specified parameters.
=> Handle Coreutils Cat

lib/Core/Dependency.cpp
Handle undefined functions : `__ctype_b_loc` and `__ctype_b_locargs`
=> Handle External Functions Called by Coreutils pr and cp

lib/Solver/Solver.cpp
Valgrind reports `Invalid read of size 1` in `Z3SolverImpl::computeInitialValues()`. This patch fixes it.
=> Fixed memory error in Z3SolverImpl::computeInitialValues()

lib/Core/Dependency.cpp, lib/Core/Dependency.h
The fix is in Dependency::recursivelyBuildAllocationGraph(). This will prevent many cases of computer crashes (frozen) due to stack overflow caused by cycles in the allocation graph.
=> Removal of 2-cycles in the construction of AllocationGraph objects

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/ITree.cpp
This is fix to #99 as well as to the assertion failure that triggered the invocation of the destructor of `Dependency` class, which triggered #99.
=> Fixed Dependency Destructor and GetElementPtr Handling for Dependency

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/ExecutionState.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
This PR is for resolving issues #9 and #12 .
I could identify some refactoring tasks to be done further, but they are for a separate PR after this one is merged. They are:
* Reimplement SubsumptionTableEntry::replaceExpr using ApplySubstitutionVisitor
* Reimplement SubsumptionTableEntry::hasSubExpression using ApplySubstitutionVisitor
* Make small methods inlined.
* `unsatCoreMarking` and `markPathCondition` possibly unifiable into the same method.
=> Code Commenting and Formatting

lib/Core/Dependency.cpp, lib/Core/Dependency.h
This is a fix for #105 , which should simplify the code. In addition, this PR also:
* ensures that `test/Runtime/POSIX/Getenv.c` and `test/Runtime/Uclibc/Environ.c` regression tests succeed. Both calls system function `getenv` whose dependency construction used to depend on `EnvironmentAllocation` class,
* contains a fix for 18 issues related to regression test (`make check`) failures (issue #13), and
* ensures that `klee-examples/basic` benchmark programs has subsumption/reported error numbers unchanged.
=> Removal of EnvironmentAllocation Class and Regression Fixes

lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
Some nice ideas borrowed from the development branch. Const methods are safer and may execute faster.
=> Made print / dump methods const

lib/Core/ITree.cpp, lib/Core/ITree.h
As suggested in https://github.com/tracer-x/klee/pull/106, this new PR made one more method as const. However, `ITree::printTimeStat , SubsumptionTableEntry::printStat`, and 
`ITreeNode::printTimeStat `actually cannot use `const` because they are static method.
=> Made ITree::dumpInterpolationStat method const

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/ITree.cpp, lib/Core/ITree.h
This PR is a refinement of https://github.com/tracer-x/klee/pull/97. This PR attempts to detect graph cycle in general. The graph cycle prevention can be done by inserting a new edge(u,v) only if there's no path between v to u.  This PR also includes handling external function which needed by `coreutils`.
=> Prevent graph cycle before adding a new edge

include/klee/IncompleteSolver.h, include/klee/Solver.h, include/klee/SolverImpl.h, lib/Core/Executor.cpp, lib/Core/Executor.h, lib/Core/ITree.h, lib/Core/SpecialFunctionHandler.cpp, lib/Core/TimingSolver.cpp, lib/Core/TimingSolver.h, lib/Solver/CLPRBuilder.cpp, lib/Solver/CLPRBuilder.h, lib/Solver/CachingSolver.cpp, lib/Solver/CexCachingSolver.cpp, lib/Solver/IndependentSolver.cpp, lib/Solver/QueryLoggingSolver.h, lib/Solver/Solver.cpp
Other edits including correcting the communication between KLEE and CLP(R) backend. Now we require that every CLP predicate has a mandatory first argument that represents the global heap of the program state. Smaller edits including making `validateRecursivePredicate` methods `const`.
=> Added -clpr-log option and other edits

lib/Core/Dependency.cpp, lib/Core/Executor.cpp, lib/Core/ITree.cpp
When `--with-z3` was not specified when running `configure`. The problem was because of interdependency of code.
=> Fixed compilation errors when --with-z3 not specified

lib/Core/ITree.cpp, lib/Core/ITree.h, lib/Core/SpecialFunctionHandler.cpp, lib/Solver/CLPRBuilder.cpp
Fixed issue #118. When negating a constraint, e.g., `(A=B)` instead of using `not(...)`, which is negation as failure, we instead modify the constraint to `(A<B);(A>B)`, that is, `A<B` or `A>B`.
Also, added subsumption edges for `klee_join` in the `tree.dot` file, where the first-proved node is labeled `(join-proved)`, and the subsumed node is labeled `(join-subsumed)`.
=> Prevents Negation as Failure for Constraints

lib/Core/Dependency.cpp
This is a fix for executing `coreutils pinky` program.
=> Handle llvmArgValue with pointer type in executePHI

lib/Core/Dependency.cpp
... by adding additional `null` sources checking in the `directLocalFlowSources` and before `addDependency` method being called
This is also a fix for `make test`, with result:
Testing Time: 617.29s
Failing Tests (8):
KLEE :: Feature/KleeReportError.c
KLEE :: Feature/MemoryLimit.c
KLEE :: Feature/OvershiftCheck.c
KLEE :: Feature/consecutive_divide_by_zero.c
KLEE :: Runtime/POSIX/DirConsistency.c
KLEE :: Runtime/POSIX/DirSeek.c
KLEE :: Runtime/POSIX/SeedAndFail.c
KLEE :: Runtime/POSIX/Write2.c
Expected Passes    : 160
Unexpected Failures: 8
`Previously (master branch) :`
Testing Time: 617.83s
Failing Tests (9):
KLEE :: Feature/KleeReportError.c
KLEE :: Feature/MemoryLimit.c
KLEE :: Feature/OvershiftCheck.c
KLEE :: …
=> Fix NULL sources at flowsToList 

include/klee/ExecutionState.h, lib/Core/Dependency.cpp, lib/Core/ExecutionState.cpp, lib/Core/SeedInfo.cpp
Fixes including:
1. Create the new constructor for `ExecutionState` that enable passing `prevPC`, as it will be used in the `addConstraint()` when Z3 Solver is enabled.
2. Register a new value as default return of `Dependency::getLatestValue()` , to avoid return a `null` value that might cause run time error
=> Fix for /Runtime/POSIX/SeedAndFail.c in the KLEE regression test

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
This PR currently has 3 main changes:
1. Change the subsumption check iterator into reverse iterator. From the observation of `klee-examples/Regexp.c `and 2 `coreutils` program. The successful subsumption check mostly occur on the newest entry. Therefore, to speed up finding the suitable entry for subsumption check, we can start searching from the end of the list where the newest entry is located.
2. Exhaustive search for all table entry on particular node for finding subsumption check may costly especially after studying the case of `klee-examples/Regexp` where the subsumption only occur mostly on the first, second, or third newest entry of the table. Therefore, I add the user option that enable user to specify the number of maximum fail subsumption (`max-fail-subsume`).
3. I also add …
=> Manage the subsumption check

lib/Solver/Solver.cpp
..for better performance
There's basically 4 method of creating a solver:
>  `Z3_mk_solver	(	Z3_context 	c	)	`
>  `Z3_mk_simple_solver	(	Z3_context 	c	)	`
>  `Z3_mk_solver_for_logic	(	Z3_context 	c, Z3_symbol 	logic) 	`
>  `Z3_mk_solver_from_tactic	(	Z3_context 	c, Z3_tactic 	t )	`
I compared the performance  3 of them :  `Z3_mk_solver	(	Z3_context 	c	)	`,  `Z3_mk_solver_for_logic	(	Z3_context 	c, Z3_symbol 	logic) 	` (ABV) , and  `Z3_mk_solver_from_tactic	(	Z3_context 	c, Z3_tactic 	t )	`.  From all three, `Z3_mk_simple_solver	(	Z3_context 	c	)	` is the one that produces fastest execution time.
There's no subsumption difference in klee-examples/basic and scalability/Regexp.
When I run scalability/Regexp with option-max-fail-subsume=3, this PR reduces the execution time from 24.43 to …
=>  Change the solver from z3_mk_solver_for_logic to Z3_mk_simple_solver 

lib/Core/ITree.h
They are: `ITreeNode::expression_type` and `ITreeNode::pair_type`.
=> Removed unused typedefs in ITree.h

lib/Core/Executor.cpp, lib/Core/ITree.cpp
.. regarding Number of solver calls and Number of subsumption check.
This Bug Fix is caused by putting the code 
```
if (InterpolationStat)
interpreterHandler->assignSubsumptionStats(ITree::getInterpolationStat());
```
before   `delete interpTree;` where the code should be put after  `delete interpTree;` because this code need to access variable `entryNumber`  and `programPointNumber` that is updated in the destructor of ITree.
=> Bug Fix for Average table entries per subsumption checkpoint and More info

lib/Core/ITree.cpp
.. as this information is actually the same with  `Number of solver calls for subsumption check `
=> Remove number of solver calls 

include/klee/IncompleteSolver.h, include/klee/Solver.h, include/klee/SolverImpl.h, include/klee/SolverStats.h, lib/Core/ITree.cpp, lib/Core/ITree.h, lib/Core/TimingSolver.cpp, lib/Core/TimingSolver.h, lib/Solver/CachingSolver.cpp, lib/Solver/CexCachingSolver.cpp, lib/Solver/DummySolver.cpp, lib/Solver/IndependentSolver.cpp, lib/Solver/QueryLoggingSolver.h, lib/Solver/STPSolver.cpp, lib/Solver/Solver.cpp, lib/Solver/SolverImpl.cpp, lib/Solver/SolverStats.cpp, lib/Solver/ValidatingSolver.cpp, lib/Solver/Z3Solver.cpp
Previously, the subsumption check statistics do not reflect the actual call to the core (Z3 backend) solver. They do now.
=> Corrected statistics for subsumption check

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/ITree.cpp, lib/Core/ITree.h
This PR resolves issue #103 and #85. Now:
1. There are no longer backward searches for memory allocation in for memory access (load/store). 
2. There is no longer backward computation to build memory dependency graph.
Both of the above are results of propagating memory allocation together with pointer value, keeping extra information in case the (LLVM) value is treated as a pointer.
Although the subsumption profile differs for basic examples in tracer-x/klee-examples, the new subsumption profile results in all expected errors reported, with `bubble.c` and `Regexp.c` still demonstrate significant search-space reduction.
=> Simplification to memory dependency computation

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/ITree.h
Added comment to explain why stack in the dependency shadow memory is not used. Also added comment for `SubsumptionTableEntry`.
=> Additional comment for `Dependency`

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/ITree.cpp, test/Feature/CompressedExprLogging.c, test/Feature/DeterministicSwitch.c, test/Feature/LinkLLVMLib.c, test/Feature/LoggingInstructions.c, test/Makefile, test/Runtime/POSIX/Isatty.c, test/Runtime/POSIX/Stdin.c, test/regression/2016-04-14-sdiv-2.c
On Ubuntu Linux 16.04 with LLVM 3.4, `make check` resulted in:
```
Testing Time: 657.98s
Expected Passes    : 181
```
with no unexpected results.
=> Resolved regression failures

lib/Core/Dependency.cpp
`make check` has no unexpected results and this commit does not change the subsumption and error counts for the basic suite of `klee-examples`.
=> Made select instruction only adds a single dependency when it is decided

lib/Core/Dependency.cpp, lib/Core/Dependency.h
The fixes are intended for eliminating assertion failures in the memory bounds interpolation.
=> Various Fixes for Stability

lib/Core/Dependency.cpp, lib/Core/Dependency.h
This is for when both arguments are pointer arguments.
=> Corrected pointer dependencies for binary operations

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/ITree.cpp, lib/Core/ITree.h
Allocation size is correct to be used in computing interpolant when checking memory validity, but incorrect for when generating interpolant from subsumption check. In that case, pointer values should be bounded by the bounds in the subsuming state instead of the allocation size.
=> Fix to memory bound interpolation in subsumption checking

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Dependency.cpp
Added `-special-function-bound-check` to limit memory bound interpolation to within `tracerx_check` function only. This option does not disable memory bound checks.
=> Option to limit memory bound interpolation to within tracerx_check function only

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h
Added content to the stack-indexed table `StackIndexedTable::print` method: previously this was missing.
=> Stack-indexed table print

lib/Core/TxTree.cpp
`callStack` should be iterated from `callStack.rbegin()` to `callStack.rend()` instead of the other way around.
=> Fixed reverse iteration of callStack in TxTreeNode::print

include/klee/ExecutionState.h, include/klee/klee.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/ExecutionState.cpp, lib/Core/Executor.cpp, lib/Core/SpecialFunctionHandler.cpp, lib/Core/SpecialFunctionHandler.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h, runtime/Runtest/intrinsics.c, tools/klee-replay/klee-replay.c, tools/klee/main.cpp
Added `tracerx_debug_subsumption` and `tracerx_debug_subsumption_off` API pair and `tracerx_debug_state` and `tracerx_debug_state` API pair for dynamically within the program setting the debugging output. For more information on these APIs, consult `include/klee/klee.h`.
=> Dynamic debugging interfaces

lib/Core/TxTree.cpp, lib/Core/TxTree.h
The new name is more appropriate, should have changed the name a while ago.
=> Renamed TxTree::currentINode to TxTree::currentTxTreeNode

include/klee/Internal/Module/VersionedValue.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h
In this new indexing for subsumption table, instead of lumping everything into binary tree which results in entries retrieved not matching the subsumption control location, we use n-ary tree indexing, which is the program's call graph, with unrolled recursive calls.
=> Corrected subsumption table indexing

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Executor.cpp
This makes test/path information generation from subsumed path optional. Resolves issue #200.
=> Added -subsumed-test option

lib/Core/Dependency.cpp, lib/Core/ExecutionState.cpp, lib/Core/Executor.cpp, lib/Core/TxTree.cpp, tools/klee/main.cpp
Limit output of subsumed tests statistics only when -subsumed-test option is given. Also removed compilation errors and warnings when ./configure is not run with --with-z3.
=> Limit subsumption test report

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Dependency.cpp
To trigger assertion value when the loaded value of LLVM `load` instruction differs between KLEE and Tracer-X.
=> Added -loaded-value-check option

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Dependency.cpp
Instead print warning on loaded value mismatch in Tracer-X.
=> Removed -loaded-value-check option

include/klee/Internal/Module/VersionedValue.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxTree.cpp, lib/Core/VersionedValue.cpp
This adds separation between allocations, where each allocation is identified by the pointer to the `Expr` object of its base address. This results in separation of allocations with the same callsites created in a loop.
=> Allocation indexing

lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/TxTree.h
Warnings are shown when `klee_make_symbolic` is executed in a loop. This is because the value of the old expression recorded by Tracer-X is compared against a fresh symbolic expression newly generated by `klee_make_symbolic` in the new iteration in `Dependency::execute`. This resolved the issue by silencing the warning for when the value comes from a call to `klee_make_symbolic`.
=> Eliminate warnings for klee_make_symbolic

lib/Core/Executor.cpp, lib/Core/TxTree.cpp, lib/Core/TxTree.h
Currently including for memory errors and assertion violations.
=> Added indicators of error paths in the DOT tree graph output

lib/Core/Dependency.cpp, lib/Core/Dependency.h
This fix nondeterminism in subumption profile. The cause is the lack of ordering in the addresses stored in the table. This fix the issue by introducing the ordered `Dependency::concretelyAddressedStoreKeys` and `Dependency::symbolicallyAddressedStoreKeys`.
=> Fix to nondeterminism in subsumption profile

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Core/TxValues.cpp
This PR implements forward domination algorithm towards resolving issue #199 and in addition, abstracts memory addresses that are dereferenced via another address. For the second issue, see example `basic/malloc3.c` of `klee-examples` repository. In this example, the malloc addresses assigned to `y` are regarded as address `*y`. In effect, we *eliminated* the malloc address from the expression. As such, they can be related at subsumption checks, as both interpolant table entry and the state to be subsumed would contain the same key.
=> Forward domination and elimination of memory mapping in interpolant

lib/Core/TxValues.cpp
This is to prevent LLVM assertion failure as follows, when `make check` is run:
```
klee: /usr/local/lib/llvm-3.4.2/src/lib/IR/Type.cpp:581: llvm::StringRef llvm::StructType::getName() const: Assertion `!isLiteral() && "Literal structs never have names"' failed.
0  klee            0x0000000000f55662 llvm::sys::PrintStackTrace(_IO_FILE*) + 50
1  klee            0x0000000000f54dd4
2  libpthread.so.0 0x00002b8783ce5390
3  libc.so.6       0x00002b8786557428 gsignal + 56
4  libc.so.6       0x00002b878655902a abort + 362
5  libc.so.6       0x00002b878654fbd7
6  libc.so.6       0x00002b878654fc82
7  klee            0x0000000000ef373b
8  klee            0x0000000000ef3754 llvm::Type::getStructName() const + 20
9  klee            0x00000000005e20cf …
```
=> Added isLiteral() check in TxStateAddress::adjustOffsetBound()

lib/Core/Executor.cpp, lib/Core/TxTree.cpp, lib/Core/TxTree.h
Resolves problem with `ExitOnErrorType.c` in #250. Following is the result of `make check` on tracerx server:
```
********************
Testing Time: 294.54s
********************
Failing Tests (2):
KLEE :: Feature/Realloc.c
KLEE :: Feature/const_array_opt1.c
Expected Passes    : 179
Unexpected Failures: 2
Makefile:49: recipe for target 'check-local' failed
make[1]: *** [check-local] Error 1
make[1]: Leaving directory '/home/dcsandr/software/klee/test'
/home/dcsandr/software/klee/Makefile.rules:1863: recipe for target 'check' failed
make: *** [check] Error 2
```
Also, all `basic` examples of `klee-examples` pass.
=> Made subsumption table entry not created when states are dumped

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Executor.cpp
It is confusing that we need to specify -interpolation-stat to get the interpolation / subsumption stats when interpolation is already enabled. This PR removes this option, and generates interpolation stats whenever it is enabled.
=> Removed -interpolation-stat option

include/klee/CommandLine.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/TxTree.cpp
Three options `-special-function-bound-interpolation`,  `-no-bound-check` and `-no-bound-interpolation` is unified into a single option `-special-function-bound-interpolation`.
For resolving tracer-x/klee#252.
@rasoolmaghareh I'm still going to test it.
=> WIP: Unified three options into one

include/klee/CommandLine.h, include/klee/Interpreter.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Executor.cpp, tools/klee/main.cpp
It does not make sense to generate tests from subsumed paths.
=> Disable generation of tests from subsumed paths

lib/Core/Dependency.cpp, lib/Core/Dependency.h
Sometimes getelementptr has negative index. This patch ignores dependencies due to such indices and corrected the handling of getelementptr in Dependency::evalConstantExpr, which was based on the wrong assumption that -1 results in a base of the pointer value.
=> Correction to the semantics of getelementptr with negative index

lib/Core/Dependency.cpp, lib/Core/TxValues.cpp
Assertion failure in TxStateAddress::adjustOffsetBound was triggered by the following example:
```
/*
* Simple regular expression matching.
*
* From:
*   The Practice of Programming
*   Brian W. Kernighan, Rob Pike
*
* This code with KLEE harness is obtained from the following
* page of the KLEE tutorial on December 2015:
*   http://klee.github.io/resources/Regexp.c.html
*/
#ifdef LLBMC
#include <llbmc.h>
#else
#include <klee/klee.h>
#endif
char _bound[4];
char *wcet;
void tracerx_check(char *p) { printf("Timing of Path:%d\n",((uint64_t)p)-((uint64_t)(&(_bound)))); *p;}
static int matchhere(char*,char*);
static int matchstar(int c, char *re, char *text) {
do {
if (matchhere(re, text)){
wcet++;   
return 1;
}
} while (*text != '\0' && (*text++ == c || c== '.'));
return 0;
}
static int …
```
=> Fix to assertion failure due to Tracer-X conservative validity check

include/klee/util/TxTreeGraph.h, lib/Core/TxTree.cpp, lib/Core/TxTreeGraph.cpp, lib/Core/TxValues.cpp
1. Now the nodes are numbered according the order of they are visited in the tree.
2. Added terminal number indexing as in [this example](http://www.comp.nus.edu.sg/~tracerx/web_files/pr267/regexp3.svg), where terminal nodes are numbered (terminal #N). The example was produced from executing [this program](http://www.comp.nus.edu.sg/~tracerx/web_files/pr267/regexp3.c).
3. Added feature to count calls to `tracerx_mark` function along the execution, also exemplified by the [same example as for No. 2](http://www.comp.nus.edu.sg/~tracerx/web_files/pr267/regexp3.svg), with `mark(s): N (+M)` where `N` is the total visitation of `tracerx_mark` function, and `+M` is the number of how many times the function is visited in the node (the number of returns from the function).
**EDIT:**
1. Corrected …
=> Improvements on the tree DOT output

include/klee/Constraints.h, include/klee/IncompleteSolver.h, include/klee/Internal/Module/TxValues.h, include/klee/Solver.h, include/klee/SolverImpl.h, include/klee/util/Assignment.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/TimingSolver.cpp, lib/Core/TimingSolver.h, lib/Core/TxStore.cpp, lib/Core/TxStore.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Expr/Constraints.cpp, lib/Solver/CachingSolver.cpp, lib/Solver/CexCachingSolver.cpp, lib/Solver/DummySolver.cpp, lib/Solver/FastCexSolver.cpp, lib/Solver/IncompleteSolver.cpp, lib/Solver/IndependentSolver.cpp, lib/Solver/QueryLoggingSolver.cpp, lib/Solver/QueryLoggingSolver.h, lib/Solver/STPSolver.cpp, lib/Solver/Solver.cpp, lib/Solver/SolverImpl.cpp, lib/Solver/ValidatingSolver.cpp, lib/Solver/Z3Solver.cpp, tools/kleaver/main.cpp
@rasoolmaghareh The over-subsumption issue that was mentioned in #260 is technically fixed with this PR. The `Regexp10.c` program of #260 terminates with `wcet` count 34 under bound size 29 and with `wcet` count 36 under bound size 32; so both terminated with memory error reported (using `-special-function-bound-interpolation` and `-exit-on-error` options).
**Please do not merge yet:** @rasoolmaghareh 
This is still a work in progress, as the fixes introduces heavy performance penalties. The next plan is to resolve #265 and then the issue with the simplification mentioned in #28 together in this PR. These are expected to improve performance. For #28, what we want to do is to copy the simplification procedure of KLEE (`ConstraintManager::simplifyExpr`), into a copy that returns an unsat …
=> Fix to over-subsumption

lib/Core/TxValues.cpp
Previously for pointer values absolute address value were displayed for all pointers in the debug information **that have no bound information**. As an example, 24984864 in the interpolant below:
```
KLEE: Storing entry for Node #7, Program Point 24052848
KLEE: ------------ Subsumption Table Entry ------------
Program point = 24052848
interpolant = (empty)
concrete store = [
address:
indirection: (none)
function/value: main/  %p = alloca %struct.Node*, align 8
stack:
offset: 0
content:
24984864
reason(s) for storage:
pointer use [main: Line 65]
]
```
After, full pointer information is provided when a value, which happens to be an interpolant, is displayed.
```
KLEE: Storing entry for Node #7, Program Point 33383536
KLEE: ------------ Subsumption Table Entry ------------
Program point = …
```
=> Corrected value print in TxInterpolantValue::print

lib/Core/TxTree.cpp
@rasoolmaghareh Some fixes to Tracer-X's own solver. At least as at tracer-x/klee@bbb6f6a1d2b09bf7a32681dc1be909235a9154a5 of #281, this reduces the number of queries with existential quantification, which is observable with `basic/malloc3.c` in `klee-examples`.
**EDIT: Corrected mentioned commit hash**
=> Solver simplification fix

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxStore.cpp, lib/Core/TxStore.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Core/TxValues.cpp
For resolving issue #278. This one is ready for review and merging. `make check` has been successful. Also, `basic/malloc3.c` of `klee-examples` expectedly results in a lot of subsumptions making the tree very thin, and `basic/pointer_struct1.c` no longer hiding any error due to over-subsumption. This replaces #281 .
**EDIT: Mention of #281**
=> Reimplementation of symbolic heap

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxStore.cpp, lib/Core/TxStore.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Core/TxValues.cpp, test/Runtime/POSIX/FD_Fail2.c
Resolves #265. `make check` succeeds and subsumption counts increase significantly for the test cases in `klee-examples/basic`, without any loss of error report. However, `validation.c` and `regexp_iterative.c` times out after 1 minute. If this PR is merged, a new issue to resolve the slowdown has to be opened.
=> Reimplementation of memory domination

lib/Core/TxTree.cpp
Made detection for non-existentially-quantified variables in the query expression (consequent) more precise in subsumption check, and avoid calling the solver in case there is no such variables, under the assumption that the bound variables in the tabled interpolant is constructed from feasible paths path conditions. 
`make check` succeeds, and this resolves issue #287.
=> More precise subsumption check 

lib/Core/TxTree.cpp, lib/Core/TxTree.h
In `SubsumptionTableEntry::subsumed()` remove quantification in case the body of a quantified query expression has no constraint with both bound and non-bound variables.
This resolves #288. For `basic/arraysimple5.c` for `fp-examples`, there is a reduction in subsumption count from 17  with tracer-x/klee@bf6461a3edc074016f4173d72a3cea699352c841 to 14 with this PR, but the space traversed decreased from 307 instructions to only 195 instructions. There are increases in subsumption counts for `basic/regexp_iterative.c` and `basic/sp.c`.
`make check` succeeds.
=> Remove quantification in case the body of a quantified query expression has no constraint with both bound and non-bound variables

lib/Core/TxStore.cpp
In `TxStore::markUsed()`, instead of triggering an assert. This resolves issue with Coreutils 6.10 `cut` run crashes due to the triggering of the assertion.
=> Skipping entries with depth larger than the current store

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxStore.cpp, lib/Core/TxValues.cpp
This is an attempt to shorten dependency paths by shortcutting values in the dependency graph that is not loaded from the memory. After this fix, `make check` becomes siginficantly faster. Before the fix:
```
Passing extra KLEE command line args: -solver-backend=z3
Testing Time: 108.40s
Expected Passes    : 181
```
After the fix:
```
Passing extra KLEE command line args: -solver-backend=z3
Testing Time: 63.15s
Expected Passes    : 181
```
All tests in the `basic` directory of `klee-examples` ran without change in the number of subsumption and error report counts.
=> Compression of dependency paths

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/TxValues.cpp
Replacement for #197 (the original source repository domainexpert/klee for the PR no longer exists). Again this results in significant performance gain (8.57s for `make check` compared to more than 100s previously), but there is currently an over-subsuming case for `basic/pointer_struct1.c`.
This PR is not ready to be merged.
=> Prevent computing pointer bound when better bound already computed

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/Executor.cpp, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Core/TxValues.cpp
In Tracer-X KLEE, a error can be masked by another error, since we generate TRUE interpolant from an error, which would subsume anything. If an error potentially exists further in the execution, due to this premature termination of the symbolic execution, coupled with the TRUE interpolant, the error would not be found. The example that shows this problem is `masked_error.c` in tracer-x/klee-examples#142.
=> Resolution to masked error problem

lib/Basic/CmdLineOptions.cpp, lib/Core/TxTree.cpp, lib/Core/TxTree.h
This resolves issue #219. However, it is tested only on a smaller version of the original example in #219, which is in tracer-x/klee-examples#143. `make` in `basic` directory of tracer-x/klee-examples#143 succeed, as well as `make check`.
=> Resolution to Missing Error Report

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxStore.cpp, lib/Core/TxTree.cpp, lib/Core/TxTree.h
In this PR, we avoid the use of `Dependency::getLatestValueForMarking()` (called from `Dependency::markAllValues()`) when interpolating on subsumption check. The use of `getLatestValue()` here is inaccurate since the core values in the interpolant are sometimes historical (not the latest), for example, the contents of the allocated memory regions in a data structure which can no longer be traversed from the most recent value of an LLVM register. `make check` succeeds, and `make` in the `basic` directory results in different subsumption count for `pointer_struct6.c`, which is an example implementing a tree.
=> Subsumption interpolation accuracy correction

include/klee/CommandLine.h, include/klee/Interpreter.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Executor.cpp, tools/klee/main.cpp
The extra tests are required for proper coverage computation using `llvm-cov` or `gcov`.
=> Added -subsumed-test option to generate tests from subsumed paths

include/klee/Internal/Module/TxValues.h, lib/Core/TxTree.cpp, lib/Core/TxValues.cpp, lib/Solver/Z3Builder.cpp, lib/Solver/Z3Builder.h, lib/Solver/Z3Solver.cpp
This resolves issue #194. `make check` succeeds and `make` in `basic` directory of `klee-examples` resulted in the increase of subsumption check counts for `pointer_symbolic.c` from 0 to 2.
=> Correction to the construction of existentially-quantified formula for Z3

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Core/TxValues.cpp
To use `uint64_t` bounds instead of `ref<Expr>` (symbolic expression) bounds, as the bounds should in most cases be concrete anyway. This shaves off the running time of `make check` on my machine by about 1 s. 
Before:
```
Passing extra KLEE command line args: -solver-backend=z3
Testing Time: 12.86s
Expected Passes    : 181
```
After:
```
Passing extra KLEE command line args: -solver-backend=z3
Testing Time: 11.89s
Expected Passes    : 181
```
Running `make` in `basic` directory of `klee-examples` does not change subsumption/error counts.
=> Simplifications to memory bounds computation

lib/Core/TxTree.cpp
The error had been causing crashes when experimenting with Coreutils. `make check` succeeds 100%, and `make` in `basic` directory of `klee-examples` does not catch divergence in subsumption and error counts.
=> Corrected the logic in SubsumptionTableEntry::makeConstraint()

lib/Core/TxTree.cpp
Crash was caused by recent fix to handle switch() instruction in #299. `make check` succeeds and `make` in `basic` directory of `klee-examples` does not change subsumption and error counts.
=> Fix to assertion failure crash with statemate.c

lib/Core/Dependency.cpp, lib/Core/Dependency.h
Inlining the content of Dependency::directFlowSources() into Dependency::markFlow() avoiding iterating twice on the internal data structures of `ref<TxStateValue> target`.
`make check` time before this update on `paella.d1.comp.nus.edu.sg` (fastest recorded of 4 runs):
```
********************
Testing Time: 27.12s
********************
Failing Tests (1):
KLEE :: Runtime/POSIX/Ioctl.c
Expected Passes    : 181
Unsupported Tests  : 1
Unexpected Failures: 1
```
After update (fastest recorded of 4 runs, 3 of which < 27s):
```
********************
Testing Time: 26.94s
********************
Failing Tests (1):
KLEE :: Runtime/POSIX/Ioctl.c
Expected Passes    : 181
Unsupported Tests  : 1
Unexpected Failures: 1
```
=> Small performance improvement by removing Dependency::directFlowSources()

include/klee/CommandLine.h, include/klee/Internal/Module/TxValues.h, lib/Basic/CmdLineOptions.cpp, lib/Core/Dependency.cpp, lib/Core/TxTree.cpp, lib/Core/TxValues.cpp
Corrected logic error in the constructor of TxStateAddress, where if address was not concrete, then concreteOffsetBound should be set to symbolic bound id. This correction triggered another issue where Tracer-X reports memory error (false positive) with `make check`, where KLEE does not report the error. Such errors are likely to be false positive. This second issue is also fixed by adding the option `-tracerx-pointer-error` option to enable such report by Tracer-X, which by default is disabled. `make check` and `make` of `basic` directory of `klee-examples` succeeded completely.
=> Tracer-X pointer error enabling

lib/Core/TxValues.cpp
This is for uniformity to TxInterpolantValue::print().
=> Added 'reason(s) for storage:' print in TxStateValue::printMinimal()

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxStore.cpp, lib/Core/TxStore.h, lib/Core/TxValues.cpp
Reimplementation according to the design discussed in #177 of memory bounds interpolation, namely:
1. Separation of values (`TxStateValue`) into 3 types:
a. Non-pointer value (has `TxStateValue::location.isNull()` true).
b. Pointer value that can be slackened (has `TxStateValue::doNotInterpolateBound` false).
c. Pointer value that cannot be slackened (has `TxStateValue::doNotInterpolateBoud` true).
2. Replacement of `std::set<ref<TxStateAddress> > TxStateValue::locations` with `ref<TxStateAddress> TxStateValue::location`.
Now a pointer can no longer depend on two or more pointer values, correcting and simplifying memory bounds interpolation (slackening). `make check` succeeds completely (slightly faster) with no change in subsumption  and error counts of `basic` examples of …
=> Correction to memory bounds interpolation

include/klee/Internal/Module/TxValues.h, include/klee/util/TxExprUtil.h, lib/Core/Dependency.h, lib/Core/TxPathCondition.cpp, lib/Core/TxPathCondition.h, lib/Core/TxStore.cpp, lib/Core/TxStore.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Core/TxValues.cpp
Some pre-solving simplification at subsumption check can be relegated to simplification when storing the interpolant to improve performance. This resolves issue #321 .
=> Apply interpolant simplification when storing entry into the table

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.h, lib/Core/TxStore.cpp, lib/Core/TxStore.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h
For resolving issue #305. This eliminates loops for state retrieval for subsumption checks altogether and simplifies the algorithm. `make check` succeeds 100% and `make` in `basic` directory of `klee-examples` reports no change in subsumption and error counts. `Regexp.c` example runs, on average of 5 runs, 0.198 s faster.
=> Check simplification

lib/Core/Executor.cpp, lib/Core/TxTree.cpp, lib/Core/TxTree.h
Can already be integrated. One is a fix to simplification, to prevent situations such as 
simplifying `(!(a=0) && !(b=0))` into `(!(a=0) && ((a=0)=(b=0)))`, which actually increases the size
of the formula. `make check` succeeds 100% and no change in the number of subsumption and
error counts in `basic` folder of `klee-examples`.
=> Two small fixes

include/klee/Internal/Module/TxValues.h, lib/Core/Dependency.cpp, lib/Core/Dependency.h, lib/Core/TxStore.cpp, lib/Core/TxStore.h
This fixes crashes with the following message when running with Coreutils (e.g., executing `make dirname.tx` in `coreutils` directory of `klee-examples` repository).
```
klee: TxStore.cpp:161: bool klee::TxStore::isInLeftSubtree(uint64_t) const: Assertion `current->depth > targetDepth && "entry should have been defined in an ancestor node"' failed.
0  libLLVM-3.4.so.1 0x00007fa0b351e042 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  libLLVM-3.4.so.1 0x00007fa0b351de34
2  libpthread.so.0  0x00007fa0b2423390
3  libc.so.6        0x00007fa0afbc2428 gsignal + 56
4  libc.so.6        0x00007fa0afbc402a abort + 362
5  libc.so.6        0x00007fa0afbbabd7
6  libc.so.6        0x00007fa0afbbac82
7  klee             0x00000000004f640b
8  klee             0x00000000004cc41f …
```
=> Fix to crashes when running with Coreutils

lib/Core/TxStore.cpp
The crashes when running with Coreutils `split` and `expand`, which showed up in the experimental results 29 November 2017.
=> Amended fix to Coreutils crashes

lib/Core/TxTree.cpp
In `TxSubsumptionTableEntry::simplifyArithmeticBody()`. This resolves crashing issues with Coreutils 6.10 `date`, `seq`, and `od`, observed in experiments run finished on 5 December 2017. `make check` succeeds 100% and `make` in `basic` directory of `klee-examples` resulted in no change in subsumption and error counts.
=> Added missing condition for simplification

.travis/stp.sh, Dockerfile
The STP build script was outdated. This pr fixed docker build by updating cmake version from `2` to `3` and updating STP build script
=> Fixed dockerfile, now tracer-x can be built using Dockerfile

lib/Module/KModule.cpp
This optimization is the caused of bug #335. The bug get's fixed with this change.
=> Removing Simplify CFG LLVM optimization. 

lib/Core/Executor.cpp
Can we merge this change in master branch? Here, we avoid to print blocks in speculation subtree.
=> Not printing Blocks in LiveBB when spec enabled

include/klee/Internal/Module/TxValues.h, include/klee/util/TxPrintUtil.h, lib/Core/Executor.cpp, lib/Core/TxDependency.cpp, lib/Core/TxDependency.h, lib/Core/TxPathCondition.cpp, lib/Core/TxPathCondition.h, lib/Core/TxPrintUtil.cpp, lib/Core/TxStore.cpp, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Core/TxValues.cpp
Removed few print statements for better readability.
=> Commented few print statements for better readability

lib/Core/Executor.cpp, lib/Core/TxTree.cpp, lib/Core/TxTree.h
This fixes a lot of candidate basic blocks incorrectly ignored for subsumption. Some fixing required for this patch and will be done after initial benchmarking.
=> fix(subsumption): missed candidate basic blocks

include/klee/util/TxTreeGraph.h, lib/Core/TxTree.cpp, lib/Core/TxTreeGraph.cpp
Before this PR, tree graphs with bb-unmerge enable have lots of unvisted nodes. This fixes it.
=> fix(TxTreeGraph): outputs accurate graph on bb-unmerge

include/klee/klee.h, include/klee/util/TxTreeGraph.h, lib/Core/SpecialFunctionHandler.cpp, lib/Core/SpecialFunctionHandler.h, lib/Core/TxTree.cpp, lib/Core/TxTree.h, lib/Core/TxTreeGraph.cpp, tools/klee/main.cpp
When study tx subsumption tables, it's important to understand the state the node is for. This PR adds new function `tracerx_node_tag` to allow user program to add tags to the TxTreeNode which are displayed in both debug-subsumption and the tree grpah. This should greatly improve our understanding and debugging process.
One usage example is `tracerx_node_tag("i=", i)` where i is the looping var. With this, it's easy to understand which iteration the TxTreeNode is for.
=> feat: tx node tags
